import { CATEGORY, COLOR } from "../utils/constants"

const EMOLIENTES = [
  {
    name: 'Cebada',
    content: 'Cebada, dulce y limón al gusto. (Pídela caliente, fría o helada).',
    price: '2.00',
    color: COLOR.BROWN,
    category: [CATEGORY.CLASSIC],
  },
  {
    name: 'Linaza',
    content: 'Linaza, cebada, boldo, alfalfa(opcional), dulce y limón al gusto.',
    price: '3.00',
    color: COLOR.GOLD,
    category: [CATEGORY.CLASSIC],
  },
  {
    name: 'Tuna',
    content: 'Tuna, linaza, cebada, uña de gato, boldo, alfalfa(opcional), dulce y limón al gusto.',
    price: '4.00',
    color: COLOR.TEAL,
    category: [CATEGORY.CLASSIC, CATEGORY.POPULAR],
  },
  {
    name: 'Sábila',
    content: 'Sábila, aceite de copaiba, muña, sangre de grado, linaza, cebada, boldo, dulce al gusto alfalfa(opcional).',
    price: '5.00',
    color: COLOR.GREEN,
    category: [CATEGORY.CLASSIC],
  },
  {
    name: 'Emo Café',
    content: 'Emoliente clásico + café.',
    price: '5.00',
    color: COLOR.BROWN,
    category: [CATEGORY.CLASSIC],
  },
  {
    name: 'Especial Clásico',
    content: 'Maca, 7 semillas, polen, miel y chía.',
    price: '6.00',
    color: COLOR.ORANGE,
    category: [CATEGORY.SPECIAL],
  },
  {
    name: 'Energizante',
    content: 'Maca negra, maca roja, 12 semillas, super omegas, miel y polen.',
    price: '8.00',
    color: COLOR.GOLD,
    category: [CATEGORY.SPECIAL, CATEGORY.POPULAR],
  },
  {
    name: 'Afrodisíaco',
    content: 'Mero macho, maca negra, huanarpo macho, ginseng y chuchuhuasi.',
    price: '10.00',
    color: COLOR.PINK,
    category: [CATEGORY.SPECIAL],
  },
  {
    name: 'Proteínas',
    content: 'Nutrisure, creatina, maca negra y 12 semillas.',
    price: '12.00',
    color: COLOR.GOLD,
    category: [CATEGORY.SPECIAL],
  },
  {
    name: 'Maca Con Leche + 12 Semillas',
    content: '',
    price: '6.00',
    color: COLOR.SKY,
    category: [CATEGORY.SPECIAL],
  },
  {
    name: 'Leche De Almendras + Té Matcha + Miel',
    content: '',
    price: '7.00',
    color: COLOR.SKY,
    category: [CATEGORY.SPECIAL],
  },
  {
    name: 'Hígado Graso / Colesterol',
    content: 'Cardo mariano, alcachofa, sábila y boldo.',
    price: '6.00',
    color: COLOR.PURPLE,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Gastritis',
    content: 'Tocosh, sábila, uña de gato y sangre de grado.',
    price: '6.00',
    color: COLOR.TEAL,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Diabetes',
    content: 'Moringa, spirulina, alpiste y tuna.',
    price: '6.00',
    color: COLOR.SKY,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Relajante',
    content: 'Ashwaganda, valeriana y citrato de magnesio.',
    price: '6.00',
    color: COLOR.PURPLE,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Riñones',
    content: 'Riñoplus, diente de león, tuna y chancapiedra.',
    price: '6.00',
    color: COLOR.PINK,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Detox',
    content: 'Clorofila, spirulina, sábila y tuna.',
    price: '7.00',
    color: COLOR.BROWN,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Huesos y Articulaciones',
    content: 'Colágeno, cartílago de tiburón y maca.',
    price: '6.00',
    color: COLOR.SKY,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Infección Urinaria',
    content: 'Arándanos, tuna y chancapiedra.',
    price: '6.00',
    color: COLOR.PINK,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Helicobacter Pylori',
    content: 'Suero de tocosh, copaiba, sábila y aceite esencial de muña.',
    price: '7.00',
    color: COLOR.TEAL,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Antigripal',
    content: 'Polen, propóleo, miel de abejas, limón, jarabe de eucalipto y kion.',
    price: '6.00',
    color: COLOR.GOLD,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Hormonas Femeninas (Menopausia)',
    content: 'Maca roja, aguaje y fenogreco.',
    price: '6.00',
    color: COLOR.PURPLE,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Adelgazante',
    content: 'Té matcha, spirulina, sábila y tuna.',
    price: '6.00',
    color: COLOR.SKY,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Próstata',
    content: 'Mashua negra, bio prost, huanarpo macho y chancapiedra.',
    price: '6.00',
    color: COLOR.TEAL,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Digestivo',
    content: 'Frutilax, chía, tuna y boldo.',
    price: '6.00',
    color: COLOR.PINK,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Antiparasitario',
    content: 'Antipax (paico, menta y hierba buena).',
    price: '5.00',
    color: COLOR.PURPLE,
    category: [CATEGORY.MEDICINAL],
  },
  {
    name: 'Purgante',
    content: '(Preparación de 15 a 20 minutos).',
    price: '10.00',
    color: COLOR.BROWN,
    category: [CATEGORY.MEDICINAL],
  },
]

export default EMOLIENTES